CREATE TABLE ${accountTable} (
	id INTEGER GENERATED BY DEFAULT AS SEQUENCE ${sequence} NOT NULL PRIMARY KEY,
	name VARCHAR(100) NOT NULL,
	currencyId INTEGER NOT NULL REFERENCES ${currencyTable}(id),
	amount INTEGER DEFAULT 0 NOT NULL,
  isService BOOLEAN DEFAULT FALSE NOT NULL,
	isDeleted BOOLEAN DEFAULT FALSE NOT NULL
);

INSERT INTO ${accountTable}(id, name, currencyId, isService) VALUES
(4, 'Наличные рубли', 1, FALSE),
(5, 'Наличные доллары', 2, FALSE),
(6, 'Наличные евро', 3, FALSE),
(7, 'Внешний мир рубли', 1, TRUE),
(8, 'Внешний мир доллары', 2, TRUE),
(9, 'Внешний мир евро', 3, TRUE);
