CREATE TABLE ${currencyTable} (
	id INTEGER GENERATED BY DEFAULT AS SEQUENCE ${sequence} NOT NULL PRIMARY KEY,
	name VARCHAR(100) NOT NULL UNIQUE,
	symbol VARCHAR(1) NOT NULL CHECK (LENGTH(symbol) = 1) UNIQUE,
	isDeleted BOOLEAN DEFAULT FALSE NOT NULL
);

INSERT INTO ${currencyTable}(id, name, symbol) VALUES
(1, 'Рубль', '₽'),
(2, 'Доллар', '$'),
(3, 'Евро', '€');
