CREATE TABLE ${rubricTable}(
	id INTEGER GENERATED BY DEFAULT AS SEQUENCE ${sequence} NOT NULL PRIMARY KEY,
	name VARCHAR(100) NOT NULL UNIQUE,
	isIncome BOOLEAN NOT NULL,
	isService BOOLEAN DEFAULT FALSE NOT NULL,
	isDeleted BOOLEAN DEFAULT FALSE NOT NULL
);

INSERT INTO ${rubricTable}(id, name, isIncome, isService) VALUES
(${accountTransferRubricId}, 'Перевод между счетами', FALSE, TRUE);